#!groovy

// Generated by IBM TransformationAdvisor
// Tue Jul 30 22:55:15 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}